name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: YONKO-SID
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          name: Generate Assets

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ✅ Generate Snake
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: YONKO-SID
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # ✅ Generate GitHub Readme Stats (requires PAT)
      - name: Generate GitHub Stats Card
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_1 }}" \
            "https://github-readme-stats.vercel.app/api?username=YONKO-SID&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true&border_radius=10" \
            -o dist/github-stats.svg

      - name: Generate Top Languages Card
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_1 }}" \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=YONKO-SID&layout=compact&langs_count=8&theme=tokyonight&border_radius=10" \
            -o dist/top-langs.svg

      # ✅ Generate Streak Stats
      - name: Generate Streak Stats
        run: |
          curl \
            "https://github-readme-streak-stats.herokuapp.com/?user=YONKO-SID&theme=tokyonight&border_radius=10" \
            -o dist/streak-stats.svg

      # ✅ Generate Profile Summary
      - name: Generate Profile Summary
        run: |
          curl \
            "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=YONKO-SID&theme=tokyonight" \
            -o dist/profile-summary.svg

      # ✅ Generate Dev Quote
      - name: Generate Random Quote
        run: |
          curl \
            "https://quotes-github-readme.vercel.app/api?type=horizontal&theme=tokyonight" \
            -o dist/quote.svg

      # ✅ Push all generated files
      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

